In [7]:
#Import Packages

import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 5000)
pd.set_option('display.width', 1000)

In [8]:
TRI_2017_df = pd.read_csv('TRI_2017_US.csv')

/Users/Mango/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (112) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
TRI_2017_df.head()

,1. YEAR,2. TRIFD,3. FRS ID,4. FACILITY NAME,5. STREET ADDRESS,6. CITY,7. COUNTY,8. ST,9. ZIP,10. BIA,11. TRIBE,12. LATITUDE,13. LONGITUDE,14. FEDERAL FACILITY,15. INDUSTRY SECTOR CODE,16. INDUSTRY SECTOR,17. PRIMARY SIC,18. SIC 2,19. SIC 3,20. SIC 4,21. SIC 5,22. SIC 6,23. PRIMARY NAICS,24. NAICS 2,25. NAICS 3,26. NAICS 4,27. NAICS 5,28. NAICS 6,29. DOC_CTRL_NUM,30. CHEMICAL,31. CAS #/COMPOUND ID,32. SRS ID,33. CLEAN AIR ACT CHEMICAL,34. CLASSIFICATION,35. METAL,36. METAL CATEGORY,37. CARCINOGEN,38. FORM TYPE,39. UNIT OF MEASURE,40. 5.1 - FUGITIVE AIR,41. 5.2 - STACK AIR,42. 5.3 - WATER,43. 5.4 - UNDERGROUND,44. 5.4.1 - UNDERGROUND CL I,45. 5.4.2 - UNDERGROUND C II-V,46. 5.5.1 - LANDFILLS,47. 5.5.1A - RCRA C LANDFILL,48. 5.5.1B - OTHER LANDFILLS,49. 5.5.2 - LAND TREATMENT,50. 5.5.3 - SURFACE IMPNDMNT,51. 5.5.3A - RCRA SURFACE IM,52. 5.5.3B - OTHER SURFACE I,53. 5.5.4 - OTHER DISPOSAL,54. ON-SITE RELEASE TOTAL,55. 6.1 - POTW - TRNS RLSE,56. 6.1 - POTW - TRNS TRT,57. POTW - TOTAL TRANSFERS,58. 6.2 - M10,59. 6.2 - M41,60. 6.2 - M62,61. 6.2 - M40 METAL,62. 6.2 - M61 METAL,63. 6.2 - M71,64. 6.2 - M81,65. 6.2 - M82,66. 6.2 - M72,67. 6.2 - M63,68. 6.2 - M66,69. 6.2 - M67,70. 6.2 - M64,71. 6.2 - M65,72. 6.2 - M73,73. 6.2 - M79,74. 6.2 - M90,75. 6.2 - M94,76. 6.2 - M99,77. OFF-SITE RELEASE TOTAL,78. 6.2 - M20,79. 6.2 - M24,80. 6.2 - M26,81. 6.2 - M28,82. 6.2 - M93,83. OFF-SITE RECYCLED TOTAL,84. 6.2 - M56,85. 6.2 - M92,86. OFF-SITE ENERGY RECOVERY T,87. 6.2 - M40 NON-METAL,88. 6.2 - M50,89. 6.2 - M54,90. 6.2 - M61 NON-METAL,91. 6.2 - M69,92. 6.2 - M95,93. OFF-SITE TREATED TOTAL,94. 6.2 - UNCLASSIFIED,95. 6.2 - TOTAL TRANSFER,96. TOTAL RELEASES,97. 8.1 - RELEASES,98. 8.1A - ON-SITE CONTAINED,99. 8.1B - ON-SITE OTHER,100. 8.1C - OFF-SITE CONTAIN,101. 8.1D - OFF-SITE OTHER R,102. 8.2 - ENERGY RECOVER ON,103. 8.3 - ENERGY RECOVER OF,104. 8.4 - RECYCLING ON SITE,105. 8.5 - RECYCLING OFF SIT,106. 8.6 - TREATMENT ON SITE,107. 8.7 - TREATMENT OFF SITE,108. PRODUCTION WSTE (8.1-8.7),109. 8.8 - ONE-TIME RELEASE,110. PROD_RATIO_OR_ ACTIVITY,111. 8.9 - PRODUCTION RATIO,112. PARENT CO NAME,113. PARENT CO DB NUM,Unnamed: 113
0,2017,77040RGSST13636,110008060560,AIRGAS USA LLC,13636 HEMPSTEAD,HOUSTON,HARRIS,TX,77040,NaN,NaN,29.846753,-95.523170,NO,4246,Chemical Wholesalers,NaN,NaN,NaN,NaN,NaN,NaN,424690,NaN,NaN,NaN,NaN,NaN,1317216328652,PROPYLENE,000115071,29009.0,NO,TRI,NO,0,NO,A,Pounds,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,AIRGAS INC,024492860,NaN
1,2017,44903NWMNT100CA,110000493573,NEWMAN TECHNOLOGY INC,100 CAIRNS RD,MANSFIELD,RICHLAND,OH,44903,NaN,NaN,40.806950,-82.517500,NO,336,Transportation Equipment,NaN,NaN,NaN,NaN,NaN,NaN,336390,336370.0,NaN,NaN,NaN,NaN,1317216422446,NICKEL,007440020,149674.0,YES,TRI,YES,1,YES,A,Pounds,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN
2,2017,32809VLVLN1929D,110000363179,PORT CONSOLIDATED INC,1929 DIRECTORS ROW,ORLANDO,ORANGE,FL,32809,NaN,NaN,28.459563,-81.403449,NO,999,Other,NaN,NaN,NaN,NaN,NaN,NaN,424720,NaN,NaN,NaN,NaN,NaN,1317216337915,CUMENE,000098828,18309.0,YES,TRI,NO,0,YES,A,Pounds,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,PORT CONSOLIDATED INC,NaN,NaN
3,2017,46540CRSTH437NM,110003096453,CLAYTON MIDDLEBURY,437 N MAIN ST,MIDDLEBURY,ELKHART,IN,46540,NaN,NaN,41.688046,-85.698466,NO,321,Wood Products,NaN,NaN,NaN,NaN,NaN,NaN,321991,NaN,NaN,NaN,NaN,NaN,1317216002042,DIISOCYANATES,N120,649715.0,YES,TRI,NO,0,NO,A,Pounds,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,BERKSHIRE HATHAWAY,118119528,NaN
4,2017,84663MCSPP1295W,110000470106,MACA SUPPLY CO,1415 W SPRING CREEK PL,SPRINGVILLE,UTAH,UT,84663,NaN,NaN,40.184980,-111.636520,NO,331,Primary Metals,NaN,NaN,NaN,NaN,NaN,NaN,331511,331513.0,NaN,NaN,NaN,NaN,1317216205462,ALUMINUM (FUME OR DUST),007429905,149476.0,NO,TRI,NO,4,NO,A,Pounds,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN

In [10]:
#Create dataframe with Unique Site ID, Latitude, and Longitude

latitude_longitude_df = TRI_2017_df[['3. FRS ID','12. LATITUDE', '13. LONGITUDE']]

latitude_longitude_df = latitude_longitude_df.dropna(axis=0)
latitude_longitude_df.reset_index(inplace=True)

latitude_longitude_df.isna().sum()

index            0
3. FRS ID        0
12. LATITUDE     0
13. LONGITUDE    0
dtype: int64

In [11]:
#This is an API request test for one latitude and longitude location
import requests

url = 'https://geo.fcc.gov/api/census/block/find'
parameters = {"lat": 40.80695, "lon": -82.5175}
response = requests.get(url, parameters)

data = response.json()

In [12]:
#Check response format, variable of interest is in 'results'
data

{'input': {'lat': 40.80695, 'lon': -82.5175},
 'results': [{'block_fips': '391390017001030',
   'bbox': [-82.520876, 40.805533, -82.516311, 40.808385],
   'county_fips': '39139',
   'county_name': 'Richland',
   'state_fips': '39',
   'state_code': 'OH',
   'state_name': 'Ohio',
   'block_pop_2015': 0,
   'amt': 'AMT005',
   'bea': 'BEA055',
   'bta': 'BTA278',
   'cma': 'CMA231',
   'eag': 'EAG004',
   'ivm': 'IVM231',
   'mea': 'MEA015',
   'mta': 'MTA016',
   'pea': 'PEA123',
   'rea': 'REA003',
   'rpc': 'RPC003',
   'vpc': 'VPC005'}]}

In [13]:
#Variable of interest is the first key
data['results']

[{'block_fips': '391390017001030',
  'bbox': [-82.520876, 40.805533, -82.516311, 40.808385],
  'county_fips': '39139',
  'county_name': 'Richland',
  'state_fips': '39',
  'state_code': 'OH',
  'state_name': 'Ohio',
  'block_pop_2015': 0,
  'amt': 'AMT005',
  'bea': 'BEA055',
  'bta': 'BTA278',
  'cma': 'CMA231',
  'eag': 'EAG004',
  'ivm': 'IVM231',
  'mea': 'MEA015',
  'mta': 'MTA016',
  'pea': 'PEA123',
  'rea': 'REA003',
  'rpc': 'RPC003',
  'vpc': 'VPC005'}]

In [14]:
#This is the FIPS code we would like to extract
data['results'][0]['block_fips']

'391390017001030'

In [15]:
#These are the latitude and longitudes that initiated the request
data['input']

{'lat': 40.80695, 'lon': -82.5175}

In [17]:
#This loop Will pull requests for any set of latitudes and longitudes
#Change the length of the loop to go through an entire dataframe
#This loop saves a file every 5000 requests
#File Names will be labeled like this'FIPs' + '_' + str(count) + '.csv'
#Files are updated and overwritten every time the loop is run
#If there is an error in the loop SAVE PROGRESS TO A DIFFERENT FILE NAME

import requests
import datetime

latitude_list = []
longitude_list = []
fips_code_list = []
timestamps_list = []
count = 0 
url = 'https://geo.fcc.gov/api/census/block/find'
for i in range(0, 5):
    parameters = {"lat": latitude_longitude_df['12. LATITUDE'][i], "lon": latitude_longitude_df['13. LONGITUDE'][i], 'showall':'false'}
    try:
        response = requests.get(url, parameters)
        data = response.json()        
        latitude_list.append(latitude_longitude_df['12. LATITUDE'][i])
        longitude_list.append(latitude_longitude_df['13. LONGITUDE'][i])
        fips_code_list.append(data['results'][0]['block_fips'])
        timestamps_list.append(datetime.datetime.utcnow())
    except:
        print('Error at index:', i)
        fips_code_list.append('Error')
    if ((len(fips_code_list) % 5000) == 0):
        FIPs_API_df = pd.DataFrame({'Latitude': latitude_list, 'Longitude': longitude_list, 'FIPS': fips_code_list, 'API_Time': timestamps_list})
        pd.DataFrame.to_csv(FIPs_API_df, 'FIPs' + '_' + str(count) + '.csv')
        count += 1
        
FIPs_API_df = pd.DataFrame({'Latitude': latitude_list, 'Longitude': longitude_list, 'FIPS': fips_code_list, 'API_Time': timestamps_list})
FIPs_API_df.head()

    Latitude   Longitude             FIPS                   API_Time
0  29.846753  -95.523170  482015217002016 2019-08-01 14:20:48.945374
1  40.806950  -82.517500  391390017001030 2019-08-01 14:20:49.043208
2  28.459563  -81.403449  120950169021031 2019-08-01 14:20:49.277011
3  41.688046  -85.698466  180390008024059 2019-08-01 14:20:49.392337
4  40.184980 -111.636520  490490029011003 2019-08-01 14:20:49.506957